version: '3'
services:
  web:
    build: backend/drf/
    volumes:
      - "/home/triklozoid/src/library/backend/drf:/app"
    ports:
     - "80"
    stdin_open: true
    tty: true
    entrypoint: uwsgi --http :80 --module library.wsgi
    hostname: library.local
  db:
    image: "postgres:11-alpine"
