from python:3 AS build

WORKDIR /app
COPY . .

RUN pip install pipenv

RUN pipenv install --system --deploy
RUN python manage.py collectstatic

FROM nginx:stable

COPY --from=build /app/static/ /var/www
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx -g 'daemon off;'"]
